labels:
  - name: "already fixed"
    description: "Issues that report already fixed bugs."
    color: "B3E88C"
  - name: "cannot reproduce"
    description: "Issues that report bugs that cannot be reproduced."
    color: "f9d0c4"
  - name: "confirmed"
    description: "Issues that report confirmed bugs."
    color: "f9d0c4"
  - name: "unverified"
    description: "Issues that report unverified bugs. Pending for inspection."
    color: "f9d0c4"
  - name: "semver:major"
    description: "PRs that contain breaking changes and should be released in the next major version."
    color: "c10f47"
  - name: "semver:minor"
    description: "PRs that contain new features and should be released in the next minor version."
    color: "e4f486"
  - name: "semver:patch"
    description: "PRs that contain bugfixes and should be released in the next patch version."
    color: "e8be8b"
  - name: "priority:critical"
    description: "Issues and PRs with maximum priority."
    color: "b60205"
  - name: "priority:high"
    description: "Issues and PRs with high priority."
    color: "d93f0b"
  - name: "priority:medium"
    description: "Issues and PRs with medium priority."
    color: "fbca04"
  - name: "priority:low"
    description: "Issues and PRs with low priority."
    color: "0e8a16"
  - name: "priority:ultra-low"
    description: "Issues and PRs with such a low priority it could be finished long after creation."
    color: "818181"
  - name: "help wanted"
    description: "Issues that need assistance from volunteers or PRs that need help to proceed."
    color: "128A0C"
  - name: "invalid"
    description: "Issues that will not be fixed or PRs that will not merge, e.g. due to backwards compatibility."
    color: "671df0"
  - name: "needs docs"
    description: "PRs that need documentation."
    color: "d4c5f9"
  - name: "needs testing"
    description: "PRs that need testing from the author or volunteers."
    color: "d93f0b"
  - name: "needs typings"
    description: "PRs that need typings."
    color: "d4c5f9"
  - name: "needs translations"
    description: "PRs that need translations."
    color: "b60205"
  - name: "stalled"
    description: "Issues and PRs that are being set aside for now for rethinking"
    color: "fbca04"
