extends:
  - "Jaronline/.github:.github/labels/standard.yml"
  - "Jaronline/.github:.github/labels/bug.yml"
  - "Jaronline/.github:.github/labels/needs.yml"
  - "Jaronline/.github:.github/labels/prefixed/semver.yml"
  - "Jaronline/.github:.github/labels/prefixed/priority.yml"
labels: []
