labels:
  - name: "critical"
    description: "Issues and PRs with maximum priority."
    color: "b60205"
  - name: "high"
    description: "Issues and PRs with high priority."
    color: "d93f0b"
  - name: "medium"
    description: "Issues and PRs with medium priority."
    color: "fbca04"
  - name: "low"
    description: "Issues and PRs with low priority."
    color: "0e8a16"
  - name: "ultra-low"
    description: "Issues and PRs with minimum priority."
    color: "818181"